instagram_celebrities = {
    "cristiano_ronaldo": {"name": "Cristiano Ronaldo", 
                          "what_they_do": "Footballer", 
                          "followers_m": 620},
    
    "lionel_messi": {"name": "Lionel Messi",
                     "what_they_do": "Footballer",
                     "followers_m": 505},
    
    "selena_gomez": {"name": "Selena Gomez", 
                     "what_they_do": "Singer and actor", 
                     "followers_m": 430},
    
    "kylie_jenner": {"name": "Kylie Jenner", "what_they_do": "Businesswoman and media personality", "followers_m": 400},
    "dwayne_johnson": {"name": "Dwayne Johnson", "what_they_do": "Actor and former wrestler", "followers_m": 395},
    "ariana_grande": {"name": "Ariana Grande", "what_they_do": "Singer", "followers_m": 380},
    "kim_kardashian": {"name": "Kim Kardashian", "what_they_do": "Media personality and entrepreneur", "followers_m": 365},
    "beyonce": {"name": "Beyoncé", "what_they_do": "Singer", "followers_m": 320},
    "khloe_kardashian": {"name": "Khloé Kardashian", "what_they_do": "Media personality", "followers_m": 310},
    "justin_bieber": {"name": "Justin Bieber", "what_they_do": "Singer", "followers_m": 295},
    "kendall_jenner": {"name": "Kendall Jenner", "what_they_do": "Model", "followers_m": 290},
    "taylor_swift": {"name": "Taylor Swift", "what_they_do": "Singer-songwriter", "followers_m": 285},
    "virat_kohli": {"name": "Virat Kohli", "what_they_do": "Cricketer", "followers_m": 270},
    "jennifer_lopez": {"name": "Jennifer Lopez", "what_they_do": "Singer and actor", "followers_m": 250},
    "nicki_minaj": {"name": "Nicki Minaj", "what_they_do": "Rapper and singer", "followers_m": 230},
    "neymar_jr": {"name": "Neymar Jr", "what_they_do": "Footballer", "followers_m": 225},
    "miley_cyrus": {"name": "Miley Cyrus", "what_they_do": "Singer and actor", "followers_m": 212},
    "katy_perry": {"name": "Katy Perry", "what_they_do": "Singer", "followers_m": 204},
    "zendaya": {"name": "Zendaya", "what_they_do": "Actor and singer", "followers_m": 185},
    "kevin_hart": {"name": "Kevin Hart", "what_they_do": "Comedian and actor", "followers_m": 178},
    "cardi_b": {"name": "Cardi B", "what_they_do": "Rapper", "followers_m": 170},
    "demi_lovato": {"name": "Demi Lovato", "what_they_do": "Singer and actor", "followers_m": 157},
    "rihanna": {"name": "Rihanna", "what_they_do": "Singer and entrepreneur", "followers_m": 150},
    "bad_bunny": {"name": "Bad Bunny", "what_they_do": "Singer and rapper", "followers_m": 145},
    "drake": {"name": "Drake", "what_they_do": "Rapper and singer", "followers_m": 143},
    "chris_brown": {"name": "Chris Brown", "what_they_do": "Singer", "followers_m": 141},
    "shraddha_kapoor": {"name": "Shraddha Kapoor", "what_they_do": "Actor", "followers_m": 92},
    "alia_bhatt": {"name": "Alia Bhatt", "what_they_do": "Actor", "followers_m": 86},
    "priyanka_chopra": {"name": "Priyanka Chopra", "what_they_do": "Actor and producer", "followers_m": 90},
    "deepika_padukone": {"name": "Deepika Padukone", "what_they_do": "Actor", "followers_m": 80},
    "kourtney_kardashian": {"name": "Kourtney Kardashian", "what_they_do": "Media personality", "followers_m": 220},
    "john_cena": {"name": "John Cena", "what_they_do": "Wrestler and actor", "followers_m": 20},
    "gal_gadot": {"name": "Gal Gadot", "what_they_do": "Actor", "followers_m": 110},
    "shakira": {"name": "Shakira", "what_they_do": "Singer", "followers_m": 92},
    "robert_downey_jr": {"name": "Robert Downey Jr.", "what_they_do": "Actor", "followers_m": 60},
    "will_smith": {"name": "Will Smith", "what_they_do": "Actor", "followers_m": 68},
    "chris_hemsworth": {"name": "Chris Hemsworth", "what_they_do": "Actor", "followers_m": 58},
    "tom_holland": {"name": "Tom Holland", "what_they_do": "Actor", "followers_m": 67},
    "emma_watson": {"name": "Emma Watson", "what_they_do": "Actor", "followers_m": 73},
    "millie_bobby_brown": {"name": "Millie Bobby Brown", "what_they_do": "Actor", "followers_m": 63},
    "billie_eilish": {"name": "Billie Eilish", "what_they_do": "Singer", "followers_m": 120},
    "dua_lipa": {"name": "Dua Lipa", "what_they_do": "Singer", "followers_m": 89},
    "ed_sheeran": {"name": "Ed Sheeran", "what_they_do": "Singer-songwriter", "followers_m": 48},
    "shah_rukh_khan": {"name": "Shah Rukh Khan", "what_they_do": "Actor", "followers_m": 47},
    "salman_khan": {"name": "Salman Khan", "what_they_do": "Actor", "followers_m": 69},
    "akshay_kumar": {"name": "Akshay Kumar", "what_they_do": "Actor", "followers_m": 67},
    "jacqueline_fernandez": {"name": "Jacqueline Fernandez", "what_they_do": "Actor", "followers_m": 69},
    "ranveer_singh": {"name": "Ranveer Singh", "what_they_do": "Actor", "followers_m": 48},
    "anushka_sharma": {"name": "Anushka Sharma", "what_they_do": "Actor and producer", "followers_m": 69},
    "urvashi_rautela": {"name": "Urvashi Rautela", "what_they_do": "Actor and model", "followers_m": 72},
    "varun_dhawan": {"name": "Varun Dhawan", "what_they_do": "Actor", "followers_m": 47},
    "hrithik_roshan": {"name": "Hrithik Roshan", "what_they_do": "Actor", "followers_m": 49},
    "tiger_shroff": {"name": "Tiger Shroff", "what_they_do": "Actor", "followers_m": 40},
    "disha_patani": {"name": "Disha Patani", "what_they_do": "Actor", "followers_m": 61},
    "kiara_advani": {"name": "Kiara Advani", "what_they_do": "Actor", "followers_m": 35},
    "sara_ali_khan": {"name": "Sara Ali Khan", "what_they_do": "Actor", "followers_m": 45},
    "janhvi_kapoor": {"name": "Janhvi Kapoor", "what_they_do": "Actor", "followers_m": 25},
    "kartik_aaryan": {"name": "Kartik Aaryan", "what_they_do": "Actor", "followers_m": 40},
    "kriti_sanon": {"name": "Kriti Sanon", "what_they_do": "Actor", "followers_m": 58},
    "sonam_kapoor": {"name": "Sonam Kapoor", "what_they_do": "Actor", "followers_m": 35},
    "parineeti_chopra": {"name": "Parineeti Chopra", "what_they_do": "Actor", "followers_m": 44},
    "ayushmann_khurrana": {"name": "Ayushmann Khurrana", "what_they_do": "Actor and singer", "followers_m": 20},
    "vicky_kaushal": {"name": "Vicky Kaushal", "what_they_do": "Actor", "followers_m": 19},
    "sidharth_malhotra": {"name": "Sidharth Malhotra", "what_they_do": "Actor", "followers_m": 32},
    "rashmika_mandanna": {"name": "Rashmika Mandanna", "what_they_do": "Actor", "followers_m": 44},
    "samantha_ruth_prabhu": {"name": "Samantha Ruth Prabhu", "what_they_do": "Actor", "followers_m": 35},
    "allu_arjun": {"name": "Allu Arjun", "what_they_do": "Actor", "followers_m": 26},
    "ram_charan": {"name": "Ram Charan", "what_they_do": "Actor", "followers_m": 14},
    "jr_ntr": {"name": "Jr NTR", "what_they_do": "Actor", "followers_m": 9},
    "yash": {"name": "Yash", "what_they_do": "Actor", "followers_m": 16},
    "vijay_deverakonda": {"name": "Vijay Deverakonda", "what_they_do": "Actor", "followers_m": 22},
    "kajal_aggarwal": {"name": "Kajal Aggarwal", "what_they_do": "Actor", "followers_m": 26},
    "tamannaah_bhatia": {"name": "Tamannaah Bhatia", "what_they_do": "Actor", "followers_m": 28},
    "pooja_hegde": {"name": "Pooja Hegde", "what_they_do": "Actor", "followers_m": 27},
    "nora_fatehi": {"name": "Nora Fatehi", "what_they_do": "Dancer and actor", "followers_m": 47},
    "diljit_dosanjh": {"name": "Diljit Dosanjh", "what_they_do": "Singer and actor", "followers_m": 21},
    "bts_official": {"name": "BTS", "what_they_do": "Music group", "followers_m": 78},
    "jungkook": {"name": "Jungkook", "what_they_do": "Singer", "followers_m": 55},
    "lisa_manobal": {"name": "Lisa", "what_they_do": "Singer and dancer", "followers_m": 104},
    "jennie_kim": {"name": "Jennie", "what_they_do": "Singer and rapper", "followers_m": 86},
    "rose_park": {"name": "Rosé", "what_they_do": "Singer", "followers_m": 82},
    "jisoo_kim": {"name": "Jisoo", "what_they_do": "Singer and actor", "followers_m": 79},
    "kim_taehyung": {"name": "V (Kim Taehyung)", "what_they_do": "Singer", "followers_m": 66},
    "park_jimin": {"name": "Jimin", "what_they_do": "Singer and dancer", "followers_m": 53},
    "min_yoongi": {"name": "Suga", "what_they_do": "Rapper and producer", "followers_m": 49},
    "kim_namjoon": {"name": "RM", "what_they_do": "Rapper and songwriter", "followers_m": 47},
    "kim_seokjin": {"name": "Jin", "what_they_do": "Singer", "followers_m": 50},
    "jung_hoseok": {"name": "J-Hope", "what_they_do": "Rapper and dancer", "followers_m": 51},
    "gigi_hadid": {"name": "Gigi Hadid", "what_they_do": "Model", "followers_m": 79},
    "bella_hadid": {"name": "Bella Hadid", "what_they_do": "Model", "followers_m": 61},
    "hailey_bieber": {"name": "Hailey Bieber", "what_they_do": "Model", "followers_m": 52},
    "zayn_malik": {"name": "Zayn Malik", "what_they_do": "Singer", "followers_m": 53},
    "niall_horan": {"name": "Niall Horan", "what_they_do": "Singer-songwriter", "followers_m": 34},
    "louis_tomlinson": {"name": "Louis Tomlinson", "what_they_do": "Singer-songwriter", "followers_m": 19},
    "harry_styles": {"name": "Harry Styles", "what_they_do": "Singer and actor", "followers_m": 49},
    "camila_cabello": {"name": "Camila Cabello", "what_they_do": "Singer", "followers_m": 64},
    "shawn_mendes": {"name": "Shawn Mendes", "what_they_do": "Singer-songwriter", "followers_m": 75},
    "paul_pogba": {"name": "Paul Pogba", "what_they_do": "Footballer", "followers_m": 62},
    "zlatan_ibrahimovic": {"name": "Zlatan Ibrahimović", "what_they_do": "Footballer", "followers_m": 64},
    "james_rodriguez": {"name": "James Rodríguez", "what_they_do": "Footballer", "followers_m": 52},
}

assert len(instagram_celebrities) == 100


